name: SPHINCS+-haraka-192f-simple
type: signature
claimed-nist-level: 2
length-public-key: 48
length-secret-key: 96
length-signature: 35664
testvectors-sha256: 296ccf34be01577eaf19358de99dc97c0fd21efcb75eda80697ac63f6977755d
nistkat-sha256: 3fda06fde66e57ece0b2fd8384c0f4e284efb9a6289da226b0bd3a1bda3e13be
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: aesni
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['aes']
