name: SPHINCS+-haraka-256s-robust
type: signature
claimed-nist-level: 2
length-public-key: 64
length-secret-key: 128
length-signature: 29792
testvectors-sha256: 68288c9ec0f3c21c5ad08aabf561fbeead75c4b53c3306a8055f5cd39c765588
nistkat-sha256: c950c06f1841ea938e9f261b7f49f9afaa43989868351c31bab9263ec42dd352
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: aesni
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['aes']
