name: SPHINCS+-haraka-128f-simple
type: signature
claimed-nist-level: 1
length-public-key: 32
length-secret-key: 64
length-signature: 17088
testvectors-sha256: cecb7f601d7161bca65ee2934254f6e43a2f36363ed8432112affe3c7ddb821b
nistkat-sha256: 2070a01d6d52e5e3bee764dd356c5dbdc3209f0d87bb7d7b57ac24e1e9eb19fd
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: aesni
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['aes']
