name: SPHINCS+-sha2-256s-robust
type: signature
claimed-nist-level: 5
length-public-key: 64
length-secret-key: 128
length-signature: 29792
testvectors-sha256: 89ec372afdc51ebd1c497e9cd1e13f930af2dae9537c6391119720ddc6adef45
nistkat-sha256: 2f61690d671671a10e6f1d32c699835c55bade752fb8e87dac01412b0b31f227
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: avx2
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['avx2']
