name: SPHINCS+-haraka-192s-robust
type: signature
claimed-nist-level: 2
length-public-key: 48
length-secret-key: 96
length-signature: 16224
testvectors-sha256: 678fc5d6f42118dada183252d03256a5b7e27253c1d0c3fc0c22818648452391
nistkat-sha256: 85640bbb27f562ac73c567a3f6c6e7bd1a4e793abbae73d53acf9728e8009bc2
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: aesni
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['aes']
