name: SPHINCS+-haraka-128s-simple
type: signature
claimed-nist-level: 1
length-public-key: 32
length-secret-key: 64
length-signature: 7856
testvectors-sha256: 588fa3f209b9e9be820c9f3181f9f85d0bf6598cab891b3d8136bff83baa785a
nistkat-sha256: 8c6ff529df678592b509844de529ef57705b1c1766e169670fbb1119903e4c77
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: aesni
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['aes']
