name: SPHINCS+-haraka-256f-simple
type: signature
claimed-nist-level: 2
length-public-key: 64
length-secret-key: 128
length-signature: 49856
testvectors-sha256: 3d06f9353eb48519412c96fbcc4987d20e5ce603a93b45d8ab25ab6dcf9b3e98
nistkat-sha256: 224bb32837841d6e72a7dfa000a56681087488f65f847b779d6bcfb4391a8375
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: aesni
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['aes']
